#1.默认

#2.最大连接数和最大线程数为1000
server:
  tomcat:
    max-connections: 1000
    max-threads: 1000
    max-http-header-size: 8192
    min-spare-threads: 100

#3.最大连接数和最大线程数为2000
#server:
#  tomcat:
#    max-connections: 2000
#    max-threads: 2000
#    max-http-header-size: 8192
#    min-spare-threads: 100

#本机window，8g + 256g ssd,在配置2时性能最优，取其为最佳Tomcat容器自身参数的优化
#maven打包项目，进行JVM优化测试
#JVM优化测试使用的启动方式三种
#方式1：java -jar demo-tomcat-optimize-0.0.1-SNAPSHOT.jar
#方式2：java -jar -server demo-tomcat-optimize-0.0.1-SNAPSHOT.jar
#方式3：java -jar -server -XX:PermSize=512M -XX:MaxPermSize=1024m -Xms2048m -Xmx2048m demo-tomcat-optimize-0.0.1-SNAPSHOT.jar
#三种方式都是直接在Windows上启动的，总的用JMeter压力测试后，从数据上来说第二种更好。。。
#JVM参数可能存在其他更优解