spring:
  datasource:
    #hikari连接池配置
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: bosPoolName
      max-lifetime: 1800000
    #数据库配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot-learn?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    #数据库2配置
    secondary:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springboot-learn-second?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456